module.exports = [
	"strapi::errors",
	{
		name: "strapi::security",
		config: {
			contentSecurityPolicy: {
				useDefaults: true,
				directives: {
					"frame-src": [
						"'self'",
						"https://www.youtube.com",
						"https://youtube.com",
						"https://www.youtube-nocookie.com",
						"vimeo.com",
						"*.vimeo.com",
						"facebook.com",
						"www.facebook.com",
					],
					"connect-src": [
						"'self'",
						"https:",
						"blob:",
						"*.strapi.io",
						"https://www.youtube.com",
						"https://youtubei.googleapis.com",
					],
					"img-src": [
						"'self'",
						"data:",
						"blob:",
						"strapi.io",
						"i.ytimg.com",
						"img.youtube.com",
					],
					"style-src": ["'self'", "'unsafe-inline'"],
					"media-src": ["'self'", "data:", "blob:"],
					"script-src": [
						"'self'",
						"blob:",
						"https:",
						"https://www.youtube.com",
						"https://s.ytimg.com",
						"https://www.google.com",
						"cdn.jsdelivr.net",
					],
					"font-src": ["'self'"],
					upgradeInsecureRequests: null,
				},
			},
		},
	},
	"strapi::cors",
	"strapi::poweredBy",
	"strapi::logger",
	"strapi::query",
	"strapi::body",
	"strapi::session",
	"strapi::favicon",
	"strapi::public",
];
